# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='current_command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.Command'),
        ),
        migrations.AddField(
            model_name='job',
            name='exit_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'not started'), (1, 'running'), (2, 'finished')], default=0, null=True),
        ),
    ]
