# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_auto_20160407_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'not started'), (1, 'running'), (2, 'finished'), (3, 'error')], default=0, null=True),
        ),
    ]
