# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_auto_20160407_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='output',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
