# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_auto_20160407_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='input',
            field=models.CharField(default='[]', max_length=10000),
        ),
    ]
