# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0006_auto_20160407_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='monitor',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Monitor'), (1, 'Slurm Monitor')], default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='scheduler_state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
